### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by pizza0rodeo** [bencall/RPlay#2]
I opened the JAR, gave it a name and hit "start", and the AirPlay icon appeared as expected on my iPhone. I was able to choose the speaker on my phone and hit the play button, but while the iPhone acted like it was playing to the remote speaker (the timeline was advancing), no sound actually came out on my computer. Here's what I saw in Console.app:

5/27/11 10:51:12 PM [0x0-0xe70e7].com.apple.JarLauncher[13522]  Registered Name  : 7c6d62902a74@icanhasairport
5/27/11 10:51:12 PM [0x0-0xe70e7].com.apple.JarLauncher[13522]             Type  : _raop._tcp.
5/27/11 10:51:12 PM [0x0-0xe70e7].com.apple.JarLauncher[13522]             Domain: local.
5/27/11 10:51:42 PM [0x0-0xe70e7].com.apple.JarLauncher[13522]  REQUEST: OPTIONS
5/27/11 10:51:42 PM [0x0-0xe70e7].com.apple.JarLauncher[13522]  OPTIONS \* RTSP/1.0
5/27/11 10:51:42 PM [0x0-0xe70e7].com.apple.JarLauncher[13522]  CSeq: 0
5/27/11 10:51:42 PM [0x0-0xe70e7].com.apple.JarLauncher[13522]  Apple-Challenge: EXb16hCGgAbfAI0S0lpt9Q==
5/27/11 10:51:42 PM [0x0-0xe70e7].com.apple.JarLauncher[13522]  DACP-ID: E834A7B4C5AE1ED7
5/27/11 10:51:42 PM [0x0-0xe70e7].com.apple.JarLauncher[13522]  Active-Remote: 2120622625
5/27/11 10:51:42 PM [0x0-0xe70e7].com.apple.JarLauncher[13522]  RTSP/1.0 200 OK
5/27/11 10:51:42 PM [0x0-0xe70e7].com.apple.JarLauncher[13522]  Audio-Jack-Status: connected; type=analog
5/27/11 10:51:42 PM [0x0-0xe70e7].com.apple.JarLauncher[13522]  CSeq: 0
5/27/11 10:51:42 PM [0x0-0xe70e7].com.apple.JarLauncher[13522]  Apple-Response: qrZngRMzkv64r4lta+7UdE/qYSacggkge6tS88PTt1dAsoFIHmGx3AW73aE+oiPoOU5O89FkUL0N43AkLpu5Byk5dILB2FTE/l3Oh+td2+u141GDiBFo+AQHCBW1YHiRuZRSy/eYPSY2FCX6Oi/dN2zKViJEAiKp1udI3HU4IO4a5+R8NpsKeMrwKKCfm9imald0ptFOoWA2hTiMoXigjEMXgesgWHFPKAiwyVnTl8fJMvCN7w7Rm+vjHAawZckRiJUt8xRNGatg55KCv/G/th/X5z4YXBGJcHwngFeJpo/tIRnQKAZwJ78U4k3ag2WtiJuwBjGX5SnjL6Djhiyk8Q
5/27/11 10:51:42 PM [0x0-0xe70e7].com.apple.JarLauncher[13522]  Public: ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER

**Comment by bencall** [comment]
It seems, like the second connection is never opened.
I can't look at it now 'cause i have exams to pass.

Tough, you can check macshairport (https://github.com/joshaber/MacShairport) which is a mac binary or https://github.com/albertz/shairport which is the original (and most advanced) shairport soft (compilation needed, but trivial).

**Comment by jblezoray** [comment]
This issue was corrected in this contribution : 
https://github.com/bencall/RPlay/commit/287dc1368421c7000412c32ddae99a1b70058973

I suggest to close this issue.
